import argparse
import json
import os
from collections import Counter
from pathlib import Path


def load_json(path, default):
    try:
        with path.open("r", encoding="utf-8") as file:
            return json.load(file)
    except Exception:
        return default


def summarize_bandit(report_dir):
    data = load_json(report_dir / "bandit.json", {})
    results = data.get("results") or []
    severities = Counter((item.get("issue_severity") or "UNKNOWN").upper() for item in results)
    confidences = Counter((item.get("issue_confidence") or "UNKNOWN").upper() for item in results)
    return {
        "total": len(results),
        "severities": severities,
        "confidences": confidences,
    }


def summarize_pip_audit(report_dir):
    data = load_json(report_dir / "pip-audit.json", {"dependencies": []})
    dependencies = data.get("dependencies") if isinstance(data, dict) else []
    vulnerable_dependencies = []
    vulnerability_count = 0

    for dependency in dependencies or []:
        vulns = dependency.get("vulns") or []
        if not vulns:
            continue
        vulnerability_count += len(vulns)
        vulnerable_dependencies.append({
            "name": dependency.get("name") or "unknown",
            "version": dependency.get("version") or "unknown",
            "count": len(vulns),
        })

    return {
        "vulnerability_count": vulnerability_count,
        "vulnerable_dependencies": vulnerable_dependencies,
    }


def summarize_detect_secrets(report_dir):
    data = load_json(report_dir / "detect-secrets.json", {"results": {}})
    results = data.get("results") if isinstance(data, dict) else {}
    findings = []

    for file_name, file_findings in (results or {}).items():
        for finding in file_findings or []:
            findings.append({
                "file": file_name,
                "line": finding.get("line_number"),
                "type": finding.get("type") or "Unknown",
            })

    return {
        "total": len(findings),
        "findings": findings,
    }


def counter_text(counter):
    if not counter:
        return "0"
    order = ["HIGH", "MEDIUM", "LOW", "UNKNOWN"]
    parts = []
    for key in order:
        if counter.get(key):
            parts.append(f"{key}: {counter[key]}")
    for key, value in sorted(counter.items()):
        if key not in order:
            parts.append(f"{key}: {value}")
    return ", ".join(parts) if parts else "0"


def build_markdown(report_dir):
    bandit = summarize_bandit(report_dir)
    pip_audit = summarize_pip_audit(report_dir)
    secrets = summarize_detect_secrets(report_dir)

    lines = [
        "# Security Analysis Summary",
        "",
        "Generated by the GitHub Actions security workflow.",
        "",
        "## Tool Results",
        "",
        "| Tool | Scope | Result |",
        "| --- | --- | --- |",
        (
            "| CodeQL | Python and JavaScript static analysis | "
            "Uploaded to GitHub Code Scanning when repository permissions allow it |"
        ),
        (
            "| Bandit | Python SAST | "
            f"{bandit['total']} findings; severity: {counter_text(bandit['severities'])}; "
            f"confidence: {counter_text(bandit['confidences'])} |"
        ),
        (
            "| pip-audit | Python dependency vulnerabilities | "
            f"{pip_audit['vulnerability_count']} known vulnerabilities across "
            f"{len(pip_audit['vulnerable_dependencies'])} dependencies |"
        ),
        (
            "| detect-secrets | Accidental secret exposure | "
            f"{secrets['total']} potential secrets detected |"
        ),
        "",
        "## Rubric Mapping",
        "",
        "- Identified risks: dependency vulnerabilities, insecure coding patterns, accidental secret exposure and weak operational configuration.",
        "- Vulnerabilities found: review the generated JSON/TXT reports in this artifact.",
        "- Mitigation proposals: update vulnerable dependencies, remove or rotate secrets, restrict CORS, disable debug mode in production and add authentication to administrative endpoints.",
        "",
        "## Evidence Files",
        "",
        "- `bandit.json` and `bandit.txt`",
        "- `pip-audit.json` and `pip-audit.txt`",
        "- `detect-secrets.json`",
        "- GitHub Code Scanning results from CodeQL, when available in the repository Security tab.",
        "",
    ]

    if pip_audit["vulnerable_dependencies"]:
        lines.extend(["## Vulnerable Dependencies", ""])
        lines.extend(["| Package | Version | Vulnerabilities |", "| --- | --- | ---: |"])
        for dependency in pip_audit["vulnerable_dependencies"]:
            lines.append(
                f"| {dependency['name']} | {dependency['version']} | {dependency['count']} |"
            )
        lines.append("")

    if secrets["findings"]:
        lines.extend(["## Potential Secrets", ""])
        lines.extend(["| File | Line | Type |", "| --- | ---: | --- |"])
        for finding in secrets["findings"][:50]:
            lines.append(f"| {finding['file']} | {finding['line']} | {finding['type']} |")
        if len(secrets["findings"]) > 50:
            lines.append(f"| ... | ... | {len(secrets['findings']) - 50} more findings |")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Build a Markdown summary from security scanner reports.")
    parser.add_argument("report_dir", type=Path, help="Directory containing generated security reports.")
    args = parser.parse_args()

    args.report_dir.mkdir(parents=True, exist_ok=True)
    summary = build_markdown(args.report_dir)
    summary_path = args.report_dir / "security-summary.md"
    summary_path.write_text(summary, encoding="utf-8")

    github_step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if github_step_summary:
        with open(github_step_summary, "a", encoding="utf-8") as file:
            file.write(summary)
            file.write("\n")

    print(summary)


if __name__ == "__main__":
    main()
